site_name: MSCR docs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - attr_list
  - md_in_html
  - tables
plugins:
  - glightbox
theme:
  name: material
  features:
    - navigation.tabs  
    - navigation.tabs.sticky    
    - navigation.sections
    - content.code.copy
nav:
  - 'Metadata schema and crosswalk registry':
    - Introduction: index.md
    - UI Guide: 'mscr/ui-guide.md'
    - Deployment: 'mscr/mscr-deployment.md'
    - MSCR Concepts: 'mscr/functional-overview.md'
    - Schema view: 'mscr/schema-view.md'
    - Crosswalk editor: 'mscr/crosswalk-editor.md'
    - Handling Common Error: 'mscr/handle-common-error.md'
    - API:
      - 'Getting started': 'mscr/api-getting-started.md'
      - 'Usage guide': 'mscr/api-usage-guide.md'
      - 'Release notes': 'mscr/release-notes.md'
  - 'Vocabulary service':
    - 'Getting started': voc-service/getting-started.md
  - 'Group management':
    - 'Getting started': groups/getting-started.md
    - 'Usage guide': groups/usage-guide.md
  - 'Developers Guide':
    - 'Getting started': developer/develop-guide.md
  - 'Service Policy':
    - 'Terms of Use': terms-of-use.md
    - 'Acceptable Use Policy': acceptable-use-policy.md
    - 'Privacy Policy': privacy-guideline.md
    
