site_name: MSCR docs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
theme:
  name: material
  features:
    - navigation.tabs  
    - navigation.tabs.sticky    
    - navigation.sections
nav:
  - 'Metadata schema and crosswalk registry':
    - Introduction: index.md
    - 'Deployment': 'mscr-deployment.md'
    - API:
      - 'Getting started': 'mscr/api-getting-started.md'
      - 'Usage guide': 'mscr/api-usage-guide.md'
  - 'Vocabulary service':
    - Deployment: 'voc-deployment.md'
  - 'Group management':
    - 'Getting started': groups/getting-started.md
    - 'Usage guide': groups/usage-guide.md
