site_name: MSCR docs
theme:
  name: material
  features:
    - navigation.tabs  
    - navigation.tabs.sticky    
    - navigation.sections
nav:
  - 'Metadata schema and crosswalk registry':
    - 'Deployment': 'mscr-deployment.md'
    - API:
      - 'Getting started': 'api-getting-started.md'
      - 'Usage guide': 'api-usage-guide.md'
  - 'Vocabulary service':
    - Deployment: 'voc-deployment.md'
